{
 "title": "Shipment Coordinator",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP success rates by route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(http_request_method, http_route, http_response_status_code) (increase(http_server_duration_milliseconds_count{http_route=~\"/api/.*\",http_response_status_code=~\"2..\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP error rates by route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(http_request_method, http_route, http_response_status_code) (increase(http_server_duration_milliseconds_count{http_route=~\"/api/.*\",http_response_status_code=~\"4..|5..\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of orders created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(order_created_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of orders updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (status) (increase(order_updated_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of contracts created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(contract_created_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}