// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/google/uuid"
	"github.com/victorvcruz/shipment-coordinator/internal/order"
	"sync"
)

// Ensure, that ServiceMock does implement order.Service.
// If this is not the case, regenerate this file with moq.
var _ order.Service = &ServiceMock{}

// ServiceMock is a mock implementation of order.Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked order.Service
//		mockedService := &ServiceMock{
//			CreateFunc: func(ctx context.Context, orderMoqParam *order.Order) (*order.Order, error) {
//				panic("mock out the Create method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*order.Order, error) {
//				panic("mock out the GetByID method")
//			},
//			UpdateStatusFunc: func(ctx context.Context, id uuid.UUID, status order.Status) error {
//				panic("mock out the UpdateStatus method")
//			},
//		}
//
//		// use mockedService in code that requires order.Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, orderMoqParam *order.Order) (*order.Order, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*order.Order, error)

	// UpdateStatusFunc mocks the UpdateStatus method.
	UpdateStatusFunc func(ctx context.Context, id uuid.UUID, status order.Status) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrderMoqParam is the orderMoqParam argument value.
			OrderMoqParam *order.Order
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// UpdateStatus holds details about calls to the UpdateStatus method.
		UpdateStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Status is the status argument value.
			Status order.Status
		}
	}
	lockCreate       sync.RWMutex
	lockGetByID      sync.RWMutex
	lockUpdateStatus sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ServiceMock) Create(ctx context.Context, orderMoqParam *order.Order) (*order.Order, error) {
	if mock.CreateFunc == nil {
		panic("ServiceMock.CreateFunc: method is nil but Service.Create was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrderMoqParam *order.Order
	}{
		Ctx:           ctx,
		OrderMoqParam: orderMoqParam,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, orderMoqParam)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedService.CreateCalls())
func (mock *ServiceMock) CreateCalls() []struct {
	Ctx           context.Context
	OrderMoqParam *order.Order
} {
	var calls []struct {
		Ctx           context.Context
		OrderMoqParam *order.Order
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *ServiceMock) GetByID(ctx context.Context, id uuid.UUID) (*order.Order, error) {
	if mock.GetByIDFunc == nil {
		panic("ServiceMock.GetByIDFunc: method is nil but Service.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedService.GetByIDCalls())
func (mock *ServiceMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// UpdateStatus calls UpdateStatusFunc.
func (mock *ServiceMock) UpdateStatus(ctx context.Context, id uuid.UUID, status order.Status) error {
	if mock.UpdateStatusFunc == nil {
		panic("ServiceMock.UpdateStatusFunc: method is nil but Service.UpdateStatus was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		Status order.Status
	}{
		Ctx:    ctx,
		ID:     id,
		Status: status,
	}
	mock.lockUpdateStatus.Lock()
	mock.calls.UpdateStatus = append(mock.calls.UpdateStatus, callInfo)
	mock.lockUpdateStatus.Unlock()
	return mock.UpdateStatusFunc(ctx, id, status)
}

// UpdateStatusCalls gets all the calls that were made to UpdateStatus.
// Check the length with:
//
//	len(mockedService.UpdateStatusCalls())
func (mock *ServiceMock) UpdateStatusCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	Status order.Status
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		Status order.Status
	}
	mock.lockUpdateStatus.RLock()
	calls = mock.calls.UpdateStatus
	mock.lockUpdateStatus.RUnlock()
	return calls
}
